version: '3'
   
services:
    # nginx
    nginx:
        image: nginx:1.10
        restart: always
        volumes:    
            - /docker/machine/volumes/nginx/conf.d/:/etc/nginx/conf.d:ro
            - /docker/machine/volumes/nginx/ssl/:/etc/nginx/ssl
            - /docker/projects:/applications
        ports: 
            - "80:80"
            - "443:443"

    # php 7.2
    php:
        image: valiniculae/php
        restart: always
        volumes:
            - /docker/projects:/applications           
            
    # node
    node:
        image: node:6
        volumes:
         - ../projects:/opt
        working_dir: /opt
        command: echo hi    
            
    # mysql
    mysql:
        image: mysql:5.7
        restart: always
        ports: 
            - "3306:3306"
        volumes:
            - ./volumes/mysql/:/var/lib/mysql
        command: --innodb-use-native-aio=0
        environment:
            MYSQL_DATABASE: vdocker
            MYSQL_ROOT_PASSWORD: secret

    
    #redis
    redis:
        image: redis:3.2
        restart: always
        ports:
            - "6379:6379"
            