#!/bin/sh

current_file_directory=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

show_menu(){

	if [ -f $current_file_directory/.env ]; then
		# load env variables
		set -o allexport; source $current_file_directory/.env; set +o allexport
	fi

	
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${MENU}**${NUMBER} 1)${MENU} create-vm ${NORMAL}                - Create a VirtualBox machine"
    echo -e "${MENU}**${NUMBER} 2)${MENU} configure-project ${NORMAL}        - Configure a project that will create a custom nginx config"
    echo -e "${MENU}**${NUMBER} 3)${MENU} change-domain-extension ${NORMAL}  - Change current domain extension (${DOMAIN_EXTENSION})"
    echo -e "${MENU}**${NUMBER} 4)${MENU} regenerate-configs ${NORMAL}       - Generate an external url for a local domain" 
    echo -e "${MENU}**${NUMBER} 5)${MENU} show-hosts-info ${NORMAL}          - Displays the config that needs to exist in the hosts file"
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${ENTER_LINE}Please enter a menu option and enter or ${RED_TEXT}enter to exit. ${NORMAL}"
    read opt
}

clear
clear
show_menu
while [ opt != '' ]
    do
    if [[ $opt = "" ]]; then 
            exit;
    else
        case $opt in
        1) clear;
        "$current_file_directory/resources/actions/create-vm.sh"
        show_menu;
        ;;
		2) clear;
        "$current_file_directory/resources/actions/add-project.sh"
        show_menu;
        ;;
		3) clear;
        "$current_file_directory/resources/actions/change-domain-extension.sh"
        show_menu;
        ;;
		4) clear;
        "$current_file_directory/resources/actions/regenerate-configs.sh"
        show_menu;
        ;;		
		5) clear;
        "$current_file_directory/resources/actions/show-hosts-config.sh"
        show_menu;
        ;;			

        x)exit;
        ;;

        \n)exit;
        ;;

        *)clear;
        show_menu;
        ;;
    esac
fi
done